### ISSUE TITLE
RadioButton not working with Angular

### ISSUE THREAD

**Issue by MGalatioto** [Tunaweza/nativescript-radiobutton#9]
# Description
I am using your library and unfortunately it does not work.

What i did:

- importing the module in my app module
- using RadioGroup, i.e. RadioButtons in my template
- tns debug android --bundle
I get following error **(Stack-trace)**
`ERROR in node_modules/nativescript-radiobutton/angular/radiogroup.component.ts(5,36): error TS2307: Cannot find module 'data/observable'.
node_modules/nativescript-radiobutton/radiogroup.ts(1,10): error TS2305: Module '"C:/Users/DIDMG/source/repos/insideBFH-Napp-2/insideBFH-Napp/ns-insidebfh-app/node_modules/nativescript-radiobutton/radiogroup"' has no exported member 'RadioGroupInterface'.
node_modules/nativescript-radiobutton/radiogroup.ts(1,31): error TS2305: Module '"C:/Users/DIDMG/source/repos/insideBFH-Napp-2/insideBFH-Napp/ns-insidebfh-app/node_modules/nativescript-radiobutton/radiogroup"' has no exported member 'RadioButtonInterface'.
node_modules/nativescript-radiobutton/radiogroup.ts(2,22): error TS2307: Cannot find module 'ui/core/view'.
node_modules/nativescript-radiobutton/radiogroup.ts(3,23): error TS2307: Cannot find module 'color'.
node_modules/nativescript-radiobutton/radiogroup.ts(4,35): error TS2307: Cannot find module 'platform'.
node_modules/nativescript-radiobutton/radiogroup.ts(5,46): error TS2307: Cannot find module 'ui/core/dependency-observable'.
node_modules/nativescript-radiobutton/radiogroup.ts(6,34): error TS2307: Cannot find module 'ui/core/proxy'.
node_modules/nativescript-radiobutton/radiogroup.ts(7,22): error TS2307: Cannot find module 'ui/styling/font'.
node_modules/nativescript-radiobutton/radiogroup.ts(8,1): error TS1202: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.
node_modules/nativescript-radiobutton/radiogroup.ts(8,24): error TS2307: Cannot find module 'ui/enums'.
node_modules/nativescript-radiobutton/radiogroup.ts(9,1): error TS1202: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.
node_modules/nativescript-radiobutton/radiogroup.ts(9,22): error TS2307: Cannot find module 'application'.
node_modules/nativescript-radiobutton/radiogroup.ts(10,29): error TS2307: Cannot find module 'ui/layouts/stack-layout'.
node_modules/nativescript-radiobutton/radiogroup.ts(11,23): error TS2307: Cannot find module 'ui/label'.
node_modules/nativescript-radiobutton/radiogroup.ts(41,21): error TS2339: Property '_getValue' does not exist on type 'RadioGroup'.
node_modules/nativescript-radiobutton/radiogroup.ts(45,14): error TS2339: Property '_setValue' does not exist on type 'RadioGroup'.
node_modules/nativescript-radiobutton/radiogroup.ts(71,60): error TS2339: Property '_context' does not exist on type 'RadioGroup'.
node_modules/nativescript-radiobutton/radiogroup.ts(188,21): error TS2339: Property '_getValue' does not exist on type 'RadioButton'.
node_modules/nativescript-radiobutton/radiogroup.ts(192,14): error TS2339: Property '_setValue' does not exist on type 'RadioButton'.
node_modules/nativescript-radiobutton/radiogroup.ts(196,21): error TS2339: Property '_getValue' does not exist on type 'RadioButton'.
node_modules/nativescript-radiobutton/radiogroup.ts(200,14): error TS2339: Property '_setValue' does not exist on type 'RadioButton'.
node_modules/nativescript-radiobutton/radiogroup.ts(204,21): error TS2339: Property '_getValue' does not exist on type 'RadioButton'.
node_modules/nativescript-radiobutton/radiogroup.ts(208,14): error TS2339: Property '_setValue' does not exist on type 'RadioButton'.
node_modules/nativescript-radiobutton/radiogroup.ts(235,61): error TS2339: Property '_context' does not exist on type 'RadioButton'.
node_modules/nativescript-radiobutton/radiogroup.ts(279,19): error TS2339: Property 'fontSize' does not exist on type 'RadioButton'.
node_modules/nativescript-radiobutton/radiogroup.ts(280,18): error TS2339: Property 'fontSize' does not exist on type 'RadioButton'.`

# My Versions
- Angular:
Angular CLI: 7.2.2
Node: 10.15.3
OS: win32 x64
Angular: 7.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router
@angular-devkit/architect    0.12.2 (cli-only)
@angular-devkit/core         7.1.4
@angular-devkit/schematics   7.1.4
@ngtools/webpack             7.2.4
@schematics/angular          7.1.4
@schematics/update           0.12.2 (cli-only)
rxjs                         6.3.3
typescript                   3.1.6
webpack                      4.27.1

- Nativescript
5.3.0

- Npm
6.8.0

**Thank you for your help!**

**Comment by Geeta-Singh** [comment]
I'm also getting the same issue 
```
node_modules/nativescript-radiobutton/angular/radiogroup.component.ts(5,36): error TS2307: Cannot find module 'data/observable'.
node_modules/nativescript-radiobutton/index.d.ts(1,22): error TS2307: Cannot find module 'ui/core/view'.
```
TNS : 5.3.4

Angular:
Angular CLI: 7.3.8
Node: 10.15.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular-devkit/architect    <error>
@angular-devkit/core         7.1.4
@angular-devkit/schematics   7.1.4
@ngtools/webpack             7.2.4
@schematics/angular          7.1.4
@schematics/update           <error>
rxjs                         6.3.3
typescript                   3.1.6
webpack                      4.27.1

**Comment by zfeng1** [comment]
I'm having the same issue. Anyone find a solution?

`System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.ZFWiFi/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: Error: Could not resolve app.component.html. Looked for: /data/data/org.nativescript.ZFWiFi/files/app/app.component.html.
System.err: File: "file:///data/data/org.nativescript.ZFWiFi/files/app/vendor.js, line: 77232, column: 12
System.err:
System.err: StackTrace:
System.err:     Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/vendor.js', line: 81016, column: 33
System.err:     Frame: function:'push.../node_modules/nativescript-angular/resource-loader.js.FileSystemResourceLoader.resolve', file:'file:///data/data/org.nativescript.ZFWiFi/fil
es/app/vendor.js', line: 77232, column: 19
System.err:     Frame: function:'push.../node_modules/nativescript-angular/resource-loader.js.FileSystemResourceLoader.get', file:'file:///data/data/org.nativescript.ZFWiFi/files/a
pp/vendor.js', line: 77218, column: 33
System.err:     Frame: function:'push.../node_modules/@angular/compiler/fesm5/compiler.js.DirectiveNormalizer._fetch', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/ven
dor.js', line: 22723, column: 43
System.err:     Frame: function:'push.../node_modules/@angular/compiler/fesm5/compiler.js.DirectiveNormalizer._preParseTemplate', file:'file:///data/data/org.nativescript.ZFWiFi/fi
les/app/vendor.js', line: 22762, column: 29
System.err:     Frame: function:'push.../node_modules/@angular/compiler/fesm5/compiler.js.DirectiveNormalizer.normalizeTemplate', file:'file:///data/data/org.nativescript.ZFWiFi/fi
les/app/vendor.js', line: 22750, column: 36
System.err:     Frame: function:'push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.loadDirectiveMetadata', file:'file:///data/data/org.nativescript.Z
FWiFi/files/app/vendor.js', line: 24942, column: 58
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/vendor.js', line: 32586, column: 55
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/vendor.js', line: 32585, column: 72
System.err:     Frame: function:'push.../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/vendo
r.js', line: 32582, column: 75
System.err:     Frame: function:'push.../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents', file:'file:///data/data/org.nativescript.ZFWiFi/
files/app/vendor.js', line: 32560, column: 36
System.err:     Frame: function:'push.../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler.compileModuleAsync', file:'file:///data/data/org.nativescript.ZFWiFi/files/app
/vendor.js', line: 32520, column: 37
System.err:     Frame: function:'push.../node_modules/@angular/platform-browser-dynamic/fesm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAsync', file:'file:///data/data/
org.nativescript.ZFWiFi/files/app/vendor.js', line: 65494, column: 31
System.err:     Frame: function:'compileNgModuleFactory__PRE_R3__', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/vendor.js', line: 51651, column: 21
System.err:     Frame: function:'push.../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/vendor.js'
, line: 51834, column: 16
System.err:     Frame: function:'_bootstrapper', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/vendor.js', line: 76354, column: 35
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/vendor.js', line: 76417, column: 19
System.err:     Frame: function:'push.../node_modules/tns-core-modules/data/observable/observable.js.Observable.notify', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/v
endor.js', line: 109789, column: 23
System.err:     Frame: function:'notifyLaunch', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/vendor.js', line: 127867, column: 17
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescri
pt.ZFWiFi/files/app/vendor.js', line: 127792, column: 28
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.ZFWiFi/
files/app/vendor.js', line: 127651, column: 14
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/frame/activity.js.NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.ZFWiFi/files/ap
p/vendor.js', line: 125564, column: 25
System.err:
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6718)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: Error: Could not resolve app.component.html. Looked for: /data/data/org.nativescript.ZFWiFi/files/app/app.component.html.
System.err: File: "file:///data/data/org.nativescript.ZFWiFi/files/app/vendor.js, line: 77232, column: 12
System.err:
System.err: StackTrace:
System.err:     Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/vendor.js', line: 81016, column: 33
System.err:     Frame: function:'push.../node_modules/nativescript-angular/resource-loader.js.FileSystemResourceLoader.resolve', file:'file:///data/data/org.nativescript.ZFWiFi/fil
es/app/vendor.js', line: 77232, column: 19
System.err:     Frame: function:'push.../node_modules/nativescript-angular/resource-loader.js.FileSystemResourceLoader.get', file:'file:///data/data/org.nativescript.ZFWiFi/files/a
pp/vendor.js', line: 77218, column: 33
System.err:     Frame: function:'push.../node_modules/@angular/compiler/fesm5/compiler.js.DirectiveNormalizer._fetch', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/ven
dor.js', line: 22723, column: 43
System.err:     Frame: function:'push.../node_modules/@angular/compiler/fesm5/compiler.js.DirectiveNormalizer._preParseTemplate', file:'file:///data/data/org.nativescript.ZFWiFi/fi
les/app/vendor.js', line: 22762, column: 29
System.err:     Frame: function:'push.../node_modules/@angular/compiler/fesm5/compiler.js.DirectiveNormalizer.normalizeTemplate', file:'file:///data/data/org.nativescript.ZFWiFi/fi
les/app/vendor.js', line: 22750, column: 36
System.err:     Frame: function:'push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.loadDirectiveMetadata', file:'file:///data/data/org.nativescript.Z
FWiFi/files/app/vendor.js', line: 24942, column: 58
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/vendor.js', line: 32586, column: 55
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/vendor.js', line: 32585, column: 72
System.err:     Frame: function:'push.../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/vendo
r.js', line: 32582, column: 75
System.err:     Frame: function:'push.../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents', file:'file:///data/data/org.nativescript.ZFWiFi/
files/app/vendor.js', line: 32560, column: 36
System.err:     Frame: function:'push.../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler.compileModuleAsync', file:'file:///data/data/org.nativescript.ZFWiFi/files/app
/vendor.js', line: 32520, column: 37
System.err:     Frame: function:'push.../node_modules/@angular/platform-browser-dynamic/fesm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAsync', file:'file:///data/data/
org.nativescript.ZFWiFi/files/app/vendor.js', line: 65494, column: 31
System.err:     Frame: function:'compileNgModuleFactory__PRE_R3__', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/vendor.js', line: 51651, column: 21
System.err:     Frame: function:'push.../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/vendor.js'
, line: 51834, column: 16
System.err:     Frame: function:'_bootstrapper', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/vendor.js', line: 76354, column: 35
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/vendor.js', line: 76417, column: 19
System.err:     Frame: function:'push.../node_modules/tns-core-modules/data/observable/observable.js.Observable.notify', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/v
endor.js', line: 109789, column: 23
System.err:     Frame: function:'notifyLaunch', file:'file:///data/data/org.nativescript.ZFWiFi/files/app/vendor.js', line: 127867, column: 17
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescri
pt.ZFWiFi/files/app/vendor.js', line: 127792, column: 28
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.ZFWiFi/
files/app/vendor.js', line: 127651, column: 14
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/frame/activity.js.NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.ZFWiFi/files/ap
p/vendor.js', line: 125564, column: 25
System.err:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
System.err:     at android.app.Activity.performCreate(Activity.java:7144)
System.err:     at android.app.Activity.performCreate(Activity.java:7135)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
System.err:     ... 11 more
`


Versions:
`[19-07-22 14:38:13.904] NativeScript Sidekick version: 1.18.0-v.2019.7.22.1
[19-07-22 14:38:26.185] Dependencies versions: NodeJS: 10.15.3, npm: 6.4.1, NativeScript CLI: 5.4.2.`
